// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efznnmazwqlkaxcsgoqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmem5ubWF6d3Fsa2F4Y3Nnb3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNTM0MTgsImV4cCI6MjA3NTgyOTQxOH0.3FoMl_Whlgd47zJ__HDjW76t31eB8VnqPG0G-yx2jnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});